name = "PinchingIdentity"
defaultTargets = ["PinchingIdentity"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#master"

[[lean_lib]]
name = "PinchingIdentity"
roots = ["MendozaLab.PinchingIdentity"]
