name = "KoopmanOperator"
defaultTargets = ["KoopmanOperator"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#master"

[[lean_lib]]
name = "KoopmanOperator"
roots = ["Mathlib.Dynamics.Ergodic.Koopman"]
